version: '3.8'

services:

  gateway:
    image: gateway
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gateway_container
    environment:
      ASPNETCORE_URLS: http://+:80
    ports:
      - 5000:80
    restart: always

