services:

  gateway:
    image: gateway
    build:
      context: .
      dockerfile: app.Dockerfile
    container_name: gateway_container
    environment:
      ASPNETCORE_URLS: http://+:80
    ports:
      - 10000:80
    restart: always

